# Generated by Django 5.0.4 on 2024-05-04 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be Alphabetic', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be Alphabetic', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be Alphabetic', regex='^[a-zA-Z]*$')]),
        ),
    ]
